// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAH4RPIlK0NupyED6tKe1VUqYQQGWNIqo',
    appId: '1:596203064480:web:d944d9a7abd9a8b95d4dc5',
    messagingSenderId: '596203064480',
    projectId: 'route-alert-ccf91',
    authDomain: 'route-alert-ccf91.firebaseapp.com',
    storageBucket: 'route-alert-ccf91.firebasestorage.app',
    measurementId: 'G-T20Y28M7C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxA8G5yxW_P29PvuXHveV5UXt8FU78SC0',
    appId: '1:596203064480:android:b69ef3c217ca5e635d4dc5',
    messagingSenderId: '596203064480',
    projectId: 'route-alert-ccf91',
    storageBucket: 'route-alert-ccf91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs59KvwlcdBaKrUkuCyryt4eRqPe3UhUY',
    appId: '1:596203064480:ios:70d63149ac0debb75d4dc5',
    messagingSenderId: '596203064480',
    projectId: 'route-alert-ccf91',
    storageBucket: 'route-alert-ccf91.firebasestorage.app',
    iosBundleId: 'com.example.routeAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs59KvwlcdBaKrUkuCyryt4eRqPe3UhUY',
    appId: '1:596203064480:ios:70d63149ac0debb75d4dc5',
    messagingSenderId: '596203064480',
    projectId: 'route-alert-ccf91',
    storageBucket: 'route-alert-ccf91.firebasestorage.app',
    iosBundleId: 'com.example.routeAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAH4RPIlK0NupyED6tKe1VUqYQQGWNIqo',
    appId: '1:596203064480:web:e9912a75870d0e465d4dc5',
    messagingSenderId: '596203064480',
    projectId: 'route-alert-ccf91',
    authDomain: 'route-alert-ccf91.firebaseapp.com',
    storageBucket: 'route-alert-ccf91.firebasestorage.app',
    measurementId: 'G-3JCY11CXWF',
  );
}
